name: "🔨 Trigger: GKI A13 5.15.123 (Full Features)"

on:
  workflow_dispatch:
  push:
    branches: [build/gki-a13-5-15-123]
    paths:
      - 'trigger-build.txt'

jobs:
  call-kernel-build:
    uses: ./.github/workflows/kernel-a13-5-15.yml
    secrets: inherit
    with:
      kernelsu_variant: "ReSukiSU"
      kernelsu_branch: "Stable(标准)"
      use_zram: true
      use_bbg: true
      use_ddk: true
      use_ntsync: true
      use_networking: true
      use_kpm: true
      cancel_susfs: false
      virtualization_support: "678"
      zram_full_algo: true
      version: ""
      build_time: ""
      called_from_main: true
